### ISSUE TITLE
Fix README.md Installation steps

### ISSUE THREAD

**Issue by segux** [Swyftx/crypto-address-validator#46]
Hi, please, can you update README.md with your real steps for install package and if you add some improvements to library?

**Comment by GusGold** [comment]
Hey @segux,

Thanks for the heads up. I've fixed up the install instructions, whoops!

The readme should already be up to date, but if you notice anything missing, please let me know!

**Comment by segux** [comment]
@GusGold  Thanks, i have one more thing to say. Im using this library into an angular app, important to import the browser .min.js if you want to compile fine the project without required modules like `stream`.

```import walletAddressValidatorMinJs from '@swyftx/api-crypto-address-validator/dist/wallet-address-validator.min.js';```

**Comment by GusGold** [comment]
Sorry, not 100% understanding you, but are you wanting the above also included in the readme?

**Comment by segux** [comment]
Could be useful for users. And i had some problems with package for that.
All projects that use webpack or similar, can be fine to notify it.

**Comment by GusGold** [comment]
No worries, I've added that in too
